name: Matrix
on: 
  push:
    branches-ignore:
      - main
      - master
jobs:
  node-version:
    strategy:
      matrix:
        os: [linux-latest, windows-latest]
        node_version: [6, 16]
        include:
          - os: linux-latest
            node_version: 6
            is_node_6: true
        exclude:
          - os: windows-latest
            node_version: 6
          - os: linux-latest
            node_version: 16
      # max-parallel: 2
      # fail-fast: true # if one of the job failed will fail all
    runs-on: ubuntu-latest 
    env:
      IS_NODE_VERSION: ${{ matrix.is_node_6 }}
    steps:
      - name: Log node version
        run: node -v
        continue-on-error: true

      - uses: actions/setup-node@v3
        with:
          # node-version: 16
          node-version: ${{ matrix.node_version }}
      
      - name: Log node version
        run: |
          node -v
          echo $IS_NODE_VERSION